import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

/// Manages device binding to restrict the app to a single computer.
///
/// Uses hardware fingerprinting (Windows MachineGuid, Linux machine-id, macOS IOPlatformUUID)
/// combined with a license key system for controlled device transfers.
class DeviceBindingService {
  static const _fingerprintKey = 'sms_device_fingerprint';
  static const _licenseKey = 'sms_license_key';
  static const _transferCodeKey = 'sms_transfer_code';

  final FlutterSecureStorage _secureStorage;

  DeviceBindingService({FlutterSecureStorage? secureStorage})
    : _secureStorage = secureStorage ?? const FlutterSecureStorage();

  /// Generate a unique hardware fingerprint for this device.
  Future<String> generateFingerprint() async {
    try {
      String rawId = '';

      if (Platform.isWindows) {
        // Read Windows MachineGuid from registry
        final result = await Process.run('reg', [
          'query',
          r'HKLM\SOFTWARE\Microsoft\Cryptography',
          '/v',
          'MachineGuid',
        ]);
        final output = result.stdout.toString();
        final match = RegExp(
          r'MachineGuid\s+REG_SZ\s+(\S+)',
        ).firstMatch(output);
        rawId = match?.group(1) ?? '';
      } else if (Platform.isLinux) {
        final file = File('/etc/machine-id');
        if (await file.exists()) {
          rawId = (await file.readAsString()).trim();
        }
      } else if (Platform.isMacOS) {
        final result = await Process.run('ioreg', [
          '-rd1',
          '-c',
          'IOPlatformExpertDevice',
        ]);
        final output = result.stdout.toString();
        final match = RegExp(
          r'"IOPlatformUUID"\s*=\s*"([^"]+)"',
        ).firstMatch(output);
        rawId = match?.group(1) ?? '';
      } else if (Platform.isAndroid) {
        // For Android, use Build.SERIAL + getprop
        final result = await Process.run('getprop', ['ro.serialno']);
        rawId = result.stdout.toString().trim();
      }

      if (rawId.isEmpty) {
        // Fallback: use hostname + platform
        rawId = '${Platform.localHostname}_${Platform.operatingSystem}';
      }

      // Hash the raw ID to create a consistent fingerprint
      final bytes = utf8.encode('sms_device_$rawId');
      return sha256.convert(bytes).toString();
    } catch (e) {
      if (kDebugMode) {
        print('DeviceBindingService: Error generating fingerprint: $e');
      }
      // Fallback fingerprint
      final bytes = utf8.encode(
        'sms_device_${Platform.localHostname}_${Platform.operatingSystem}',
      );
      return sha256.convert(bytes).toString();
    }
  }

  /// Get the device hostname for display purposes.
  String getDeviceName() {
    try {
      return Platform.localHostname;
    } catch (_) {
      return 'Unknown Device';
    }
  }

  /// Get OS info for display purposes.
  String getOsInfo() {
    return '${Platform.operatingSystem} ${Platform.operatingSystemVersion}';
  }

  /// Store the device fingerprint after initial binding.
  Future<void> bindDevice(String fingerprint) async {
    await _secureStorage.write(key: _fingerprintKey, value: fingerprint);
  }

  /// Read the stored fingerprint.
  Future<String?> getStoredFingerprint() async {
    return _secureStorage.read(key: _fingerprintKey);
  }

  /// Store the license key.
  Future<void> storeLicenseKey(String licenseKey) async {
    await _secureStorage.write(key: _licenseKey, value: licenseKey);
  }

  /// Read the stored license key.
  Future<String?> getStoredLicenseKey() async {
    return _secureStorage.read(key: _licenseKey);
  }

  /// Generate a license key from the fingerprint.
  /// The developer uses this to create a key for the customer.
  String generateLicenseKey(String fingerprint) {
    final bytes = utf8.encode('sms_license_$fingerprint');
    final hash = sha256.convert(bytes).toString();
    // Format as XXXX-XXXX-XXXX-XXXX for readability
    return '${hash.substring(0, 4)}-${hash.substring(4, 8)}-${hash.substring(8, 12)}-${hash.substring(12, 16)}'
        .toUpperCase();
  }

  /// Validate a license key against the device fingerprint.
  bool validateLicenseKey(String licenseKey, String fingerprint) {
    final expected = generateLicenseKey(fingerprint);
    return licenseKey.toUpperCase() == expected.toUpperCase();
  }

  /// Validate a developer transfer code.
  /// The transfer code is a special code that allows unbinding from the current device.
  bool validateTransferCode(String transferCode, String currentFingerprint) {
    // The transfer code is generated by the developer using a master secret
    final expectedCode = _generateTransferCode(currentFingerprint);
    return transferCode.toUpperCase() == expectedCode.toUpperCase();
  }

  /// Generate the transfer code for a given fingerprint.
  /// This would normally be done by the developer on their end.
  String _generateTransferCode(String fingerprint) {
    final bytes = utf8.encode('sms_transfer_master_${fingerprint}_2026');
    final hash = sha256.convert(bytes).toString();
    return '${hash.substring(0, 4)}-${hash.substring(4, 8)}-${hash.substring(8, 12)}'
        .toUpperCase();
  }

  /// Check if the device is bound.
  Future<bool> isDeviceBound() async {
    final storedFingerprint = await getStoredFingerprint();
    return storedFingerprint != null && storedFingerprint.isNotEmpty;
  }

  /// Verify current device matches the bound device.
  Future<DeviceBindingStatus> verifyBinding() async {
    final storedFingerprint = await getStoredFingerprint();

    if (storedFingerprint == null || storedFingerprint.isEmpty) {
      return DeviceBindingStatus.unbound;
    }

    final currentFingerprint = await generateFingerprint();
    if (currentFingerprint == storedFingerprint) {
      return DeviceBindingStatus.bound;
    } else {
      return DeviceBindingStatus.mismatch;
    }
  }

  /// Unbind the current device (used during transfer).
  Future<void> unbindDevice() async {
    await _secureStorage.delete(key: _fingerprintKey);
    await _secureStorage.delete(key: _licenseKey);
    await _secureStorage.delete(key: _transferCodeKey);
  }
}

/// Status of device binding verification.
enum DeviceBindingStatus {
  /// Device is not bound yet (first launch).
  unbound,

  /// Device fingerprint matches — authorized.
  bound,

  /// Device fingerprint does NOT match — unauthorized.
  mismatch,
}
